/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '江望平' at '17-5-14 下午8:13' with Gradle 2.14.1
 *
 * @author 江望平, @date 17-5-14 下午8:13
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
